# Generated by Django 5.2.6 on 2025-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.CharField(blank=True, choices=[('plomberie', 'Plomberie'), ('electricite', 'Électricité'), ('menuiserie', 'Menuiserie'), ('peinture', 'Peinture'), ('maconnerie', 'Maçonnerie'), ('jardinage', 'Jardinage'), ('climatisation', 'Climatisation'), ('carrelage', 'Carrelage'), ('nettoyage', 'Nettoyage'), ('serrurerie', 'Serrurerie')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('artisan', 'Artisan'), ('client', 'Client')], default='customer', max_length=20),
        ),
    ]
