# Generated by Django 5.2.6 on 2025-10-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_service_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('all', 'Toutes les villes'), ('douala', 'Douala'), ('yaounde', 'Yaoundé'), ('bafoussam', 'Bafoussam'), ('bamenda', 'Bamenda'), ('garoua', 'Garoua'), ('maroua', 'Maroua'), ('ngaoundere', 'Ngaoundéré'), ('bertoua', 'Bertoua'), ('ebolowa', 'Ebolowa'), ('kumba', 'Kumba')], max_length=100, null=True),
        ),
    ]
