# Generated by Django 5.2.6 on 2025-09-30 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handyman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Rate per hour in XAF', max_digits=8)),
                ('skills', models.TextField(help_text='List your skills separated by commas')),
                ('availability', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('id_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('portfolio_images', models.TextField(blank=True, help_text='URLs of portfolio images separated by commas', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'handyman_handyman',
            },
        ),
        migrations.CreateModel(
            name='HandymanRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'handyman_handymanrating',
            },
        ),
        migrations.CreateModel(
            name='HandymanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in XAF', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'handyman_handymanservice',
            },
        ),
    ]
