# Generated by Django 5.2.6 on 2025-09-30 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_initial'),
        ('customer', '0002_initial'),
        ('handyman', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='handyman',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handyman_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='handymanrating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='handymanrating',
            name='handyman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='handyman.handyman'),
        ),
        migrations.AddField(
            model_name='handymanrating',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.project'),
        ),
        migrations.AddField(
            model_name='handymanservice',
            name='handyman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='handyman.handyman'),
        ),
        migrations.AddField(
            model_name='handymanservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.service'),
        ),
        migrations.AlterUniqueTogether(
            name='handymanrating',
            unique_together={('handyman', 'customer', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='handymanservice',
            unique_together={('handyman', 'service')},
        ),
    ]
