# Generated by Django 5.2.6 on 2025-09-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handyman',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per hour in XAF', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='handyman',
            name='skills',
            field=models.TextField(blank=True, help_text='List your skills separated by commas', null=True),
        ),
    ]
