# Generated by Django 5.2.6 on 2025-10-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_project_budget_max_alter_project_budget_min'),
        ('handyman', '0003_alter_handyman_hourly_rate_alter_handyman_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandymanNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_project', 'New Project'), ('project_update', 'Project Update'), ('message', 'Message')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='handyman.handyman')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.project')),
            ],
            options={
                'db_table': 'handyman_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
