# Generated by Django 5.2.6 on 2025-10-08 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_project_city_alter_project_priority_and_more'),
        ('handyman', '0004_handymannotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handymannotification',
            name='notification_type',
            field=models.CharField(choices=[('new_project', 'New Project'), ('project_update', 'Project Update'), ('message', 'Message'), ('offer_status', 'Offer Status')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text="Message d'accompagnement de votre offre")),
                ('proposed_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Budget proposé en XAF', max_digits=10, null=True)),
                ('estimated_duration', models.CharField(blank=True, help_text='Durée estimée (ex: 2 jours, 1 semaine)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('withdrawn', 'Retirée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='handyman.handyman')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='customer.project')),
            ],
            options={
                'db_table': 'handyman_projectoffer',
                'ordering': ['-created_at'],
                'unique_together': {('handyman', 'project')},
            },
        ),
    ]
