# Generated by Django 5.2.6 on 2025-10-08 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0005_alter_handymannotification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandymanPortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Images du portfolio', upload_to='handyman_portfolio/')),
                ('title', models.CharField(blank=True, help_text='Titre du projet/travail', max_length=200, null=True)),
                ('description', models.CharField(blank=True, help_text='Description du travail réalisé', max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('handyman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images_set', to='handyman.handyman')),
            ],
            options={
                'db_table': 'handyman_portfolio_image',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
