# Generated by Django 5.2.6 on 2025-09-30 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_initial'),
        ('customer', '0001_initial'),
        ('handyman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='handyman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handyman.handyman'),
        ),
        migrations.AddField(
            model_name='billing',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='customer.project'),
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.project'),
        ),
    ]
