# Generated by Django 5.2.6 on 2025-09-30 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_initial'),
        ('customer', '0001_initial'),
        ('handyman', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='project',
            name='handyman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='handyman.handyman'),
        ),
        migrations.AddField(
            model_name='projectservice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='customer.project'),
        ),
        migrations.AddField(
            model_name='projectservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.service'),
        ),
        migrations.AlterUniqueTogether(
            name='projectservice',
            unique_together={('project', 'service')},
        ),
    ]
