# Generated by Django 5.2.6 on 2025-10-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget in XAF', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget in XAF', max_digits=10, null=True),
        ),
    ]
