# Generated by Django 5.2.6 on 2025-10-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_project_budget_max_alter_project_budget_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.CharField(choices=[('plomberie', 'Plomberie'), ('electricite', 'Électricité'), ('menuiserie', 'Menuiserie'), ('peinture', 'Peinture'), ('maconnerie', 'Maçonnerie'), ('jardinage', 'Jardinage'), ('climatisation', 'Climatisation'), ('carrelage', 'Carrelage'), ('nettoyage', 'Nettoyage'), ('serrurerie', 'Serrurerie')], default='plumbing', max_length=50),
        ),
        migrations.DeleteModel(
            name='ProjectService',
        ),
    ]
