# Generated by Django 5.2.6 on 2025-10-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_project_service_delete_projectservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, choices=[('all', 'Toutes les villes'), ('douala', 'Douala'), ('yaounde', 'Yaoundé'), ('bafoussam', 'Bafoussam'), ('bamenda', 'Bamenda'), ('garoua', 'Garoua'), ('maroua', 'Maroua'), ('ngaoundere', 'Ngaoundéré'), ('bertoua', 'Bertoua'), ('ebolowa', 'Ebolowa'), ('kumba', 'Kumba')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(choices=[('adamawa', 'Adamawa'), ('centre', 'Centre'), ('east', 'East'), ('far_north', 'Far North'), ('littoral', 'Littoral'), ('north', 'North'), ('northwest', 'Northwest'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West')], max_length=20),
        ),
    ]
