# Generated by Django 5.2.6 on 2025-10-08 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_project_city_alter_project_priority_and_more'),
        ('handyman', '0005_alter_handymannotification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_offer', 'New Offer'), ('offer_update', 'Offer Update'), ('project_update', 'Project Update'), ('message', 'Message')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customer.customer')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handyman.projectoffer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.project')),
            ],
            options={
                'db_table': 'customer_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
