# Generated by Django 5.2.6 on 2025-10-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Images du projet', upload_to='project_images/')),
                ('description', models.CharField(blank=True, help_text="Description de l'image", max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='customer.project')),
            ],
            options={
                'db_table': 'customer_project_image',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
